### ISSUE TITLE
Viewer video output broken on X11

### ISSUE THREAD

**Issue by sankhakarfa** [AravisProject/aravis#345] opened 2020-04-20 21:24 UTC
I am getting a black or glitch viewer when using arv viewer

When I open the arv-viewer-0.8 from terminal and use the default Fake camera or connect any Machine vision camera and press the play Button.

**Platform description:**
 - Aravis version V 0.7.4
 - OS: Ubuntu 18.04
 - Hardware MSI PS63 Modern 8SC

**Additional context**
This happens with aravis version 0.6 also.

![Screenshot from 2020-04-21 02-47-37](https://user-images.githubusercontent.com/6041909/79801256-6a8c0a00-837b-11ea-96eb-b92fc5042118.png)

**Comment by EmmanuelP** [comment] 2020-04-21 07:48
Do you use X11 or wayland ?

The video widget based on gtksink gstreamer element is broken. It is slow and does not work reliably on X11.

**Comment by sankhakarfa** [comment] 2020-04-21 10:20
Hi,
It changed to X11 after ubuntu 18.04 upgrade.
Changing it to wayland works fine now.
You can mark it closed now.
Also why arv-viewer is version 0.8 but the release is v0.7.4?

**Comment by EmmanuelP** [comment] 2020-04-21 10:28
I'm keeping this bug open, as we should also support X11.

> Also why arv-viewer is version 0.8 but the release is v0.7.4?

0.8 is the stable series. 0.7.x are unstable development releases, where API may break at any time.

Thanks for the report.

**Comment by AntonioMichaelAlvarez** [comment] 2021-03-19 08:16
Same issue on several machines running Ubuntu 18.04.5 LTS. All using X11 and latest available versions of XFCE or LXDE environments.

**Comment by EmmanuelP** [comment] 2021-03-19 08:45
Works for me on Ubuntu 20.10, using X11.

![image](https://user-images.githubusercontent.com/136864/111753718-7b007980-8897-11eb-9a65-632058f155e9.png)

I personally don't have the time for debugging the viewer on every distributions. Any help in this area appreciated !

**Comment by EmmanuelP** [comment] 2021-03-19 08:47
I'm closing this bug, as it doesn't seem a generic X11 related issue, but most probably a bug in gtk3 X11 support in Ubuntu 16.04.

**Closed by EmmanuelP** 2021-03-19 08:47 UTC
Labels: 1. bug, 5. Viewer

**Comment by EmmanuelP** [comment] 2022-04-10 06:41
https://aravis-project.discourse.group/t/arv-viewer-video-display-problems/89/5

On ubuntu, the issue is fixed by installing gstreamer1.0-gtk3

**Comment by nznobody** [comment] 2022-04-12 00:49
Thanks, this helped me too!
