### ISSUE TITLE
genicam: out-of-range value is set before min/max is evaluated

### ISSUE THREAD

**Issue by eudoxos** [AravisProject/aravis#456] opened 2020-12-02 13:54 UTC
**Describe the bug**
I have the VRmagic LineScan3D camera; I believe its firmware runs the GigEVision stack by Stemmer Imaging, but I am not sure.

The camera has `AOIHeight` and `AOIRowOffset` which have this constraint: `AOIRowOffset`+`AOIHeight` <= `ImageSensorHeight`. This is expressed in the XML as follows (relevant parts copied):

```xml
  <Integer Name="AOIHeight">
    <ToolTip>AOI Height of sensor in pixels</ToolTip>
    <Description>AOI Height of sensor in pixels</Description>
    <DisplayName>AOI Height</DisplayName>
    <Streamable>Yes</Streamable>
    <pValue>AOIHeightReg</pValue>
    <Min>2</Min>
    <pMax>HeightMAX</pMax>
    <Inc>2</Inc>
    <Representation>Linear</Representation>
  </Integer>
  <IntReg Name="AOIHeightReg">
    <pIsLocked>AcqEnabledReg</pIsLocked>
    <Streamable>Yes</Streamable>
    <Address>0xC13C</Address>
    <Length>4</Length>
    <AccessMode>RW</AccessMode>
    <pPort>Device</pPort>
    <pInvalidator>UserSetLoad</pInvalidator>
    <Sign>Signed</Sign>
    <Endianess>BigEndian</Endianess>
    <Representation>PureNumber</Representation>
  </IntReg>

  <Integer Name="AOIRowOffset">
    <ToolTip>AOI row offset on sensor in pixels</ToolTip>
    <Description>AOI row offset on sensor in pixels</Description>
    <DisplayName>AOI Row Offset</DisplayName>
    <Streamable>Yes</Streamable>
    <pValue>AOIRowOffsetReg</pValue>
    <Min>0</Min>
    <pMax>OffSetYMAX</pMax>
    <Inc>2</Inc>
    <Representation>Linear</Representation>
  </Integer>
  <IntReg Name="AOIRowOffsetReg">
    <pIsLocked>AcqEnabledReg</pIsLocked>
    <Streamable>Yes</Streamable>
    <Address>0xC134</Address>
    <Length>4</Length>
    <AccessMode>RW</AccessMode>
    <pPort>Device</pPort>
    <pInvalidator>UserSetLoad</pInvalidator>
    <Sign>Signed</Sign>
    <Endianess>BigEndian</Endianess>
    <Representation>PureNumber</Representation>
  </IntReg>

  <Integer Name="ImageSensorHeight">
    <ToolTip>Height in pixel of the CMOS image sensor</ToolTip>
    <Description>Height in pixel of the CMOS image sensor</Description>
    <DisplayName>Image Sensor Height</DisplayName>
    <Visibility>Expert</Visibility>
    <pValue>ImageSensorHeightReg</pValue>
    <Min>1088</Min>
    <Max>1088</Max>
    <Inc>0</Inc>
    <Representation>Linear</Representation>
  </Integer>
  <IntReg Name="ImageSensorHeightReg">
    <Visibility>Expert</Visibility>
    <Address>0xC250</Address>
    <Length>4</Length>
    <AccessMode>RO</AccessMode>
    <pPort>Device</pPort>
    <Sign>Signed</Sign>
    <Endianess>BigEndian</Endianess>
    <Representation>PureNumber</Representation>
  </IntReg>

  <IntSwissKnife Name="HeightMAX">
    <pVariable Name="OFFSETY">AOIRowOffset</pVariable>
    <pVariable Name="SENSORHEIGHT">ImageSensorHeight</pVariable>
    <Formula>SENSORHEIGHT - OFFSETY</Formula>
    <Representation>PureNumber</Representation>
  </IntSwissKnife>

  <IntSwissKnife Name="OffSetYMAX">
    <pVariable Name="HEIGHT">AOIHeight</pVariable>
    <pVariable Name="SENSORHEIGHT">ImageSensorHeight</pVariable>
    <Formula>SENSORHEIGHT - HEIGHT</Formula>
    <Representation>PureNumber</Representation>
  </IntSwissKnife>
```
I tried to run with `./arv-tool-0.8 control AOIRowOffset=0 AOIHeight=1088 -d evaluator:3` getting this:

```
[Evaluator::set_double_variable] PI = 3.14159
[Evaluator::set_double_variable] E = 2.71828
[...]
VRmagicImaging-VRmLS1-GEV#128#018-660#C-EFD0AFMH07 (169.254.21.101)
[Evaluator::set_int64_variable] SENSORHEIGHT = 1088
[Evaluator::set_int64_variable] HEIGHT = 1088
[Evaluator::evaluate_as_int64] Expression = 'SENSORHEIGHT - HEIGHT'
[Evaluator::parse_expression] SENSORHEIGHT - HEIGHT
[Evaluator::parse_expression] Found 3 items in expression
[Evaluator::parse_expression] 0 items in garbage list
[Evaluator::parse_expression] 3 items in token list
[Evaluator::evaluate_as_int64] Parsing status = 0
(var) SENSORHEIGHT = 1088
(var) HEIGHT = 1088
(operator) -
[Evaluator::evaluate] Result = (int64) 0
AOIRowOffset = 0 min:0 max:0 inc:2
[Evaluator::set_int64_variable] SENSORHEIGHT = 1088
[Evaluator::set_int64_variable] OFFSETY = 0
[Evaluator::evaluate_as_int64] Expression = 'SENSORHEIGHT - OFFSETY'
[Evaluator::parse_expression] SENSORHEIGHT - OFFSETY
[Evaluator::parse_expression] Found 3 items in expression
[Evaluator::parse_expression] 0 items in garbage list
[Evaluator::parse_expression] 3 items in token list
[Evaluator::evaluate_as_int64] Parsing status = 0
(var) SENSORHEIGHT = 1088
(var) OFFSETY = 0
(operator) -
[Evaluator::evaluate] Result = (int64) 1088
AOIHeight = 1088 min:2 max:1088 inc:2
```
This look correct and works. Initial height is 1088 (full sensor), thus `AOIRowOffset` is capped at 0 (`AOIRowOffset = 0 min:0 max:0 inc:2`) and `AOIHeight` is `AOIHeight = 1088 min:2 max:1088 inc:2`.

**To Reproduce**
I try to set invalid value now, e.g. like this: `./arv-tool-0.8 control AOIRowOffset=2000 -d evaluator:3`:

```
VRmagicImaging-VRmLS1-GEV#128#018-660#C-EFD0AFMH07 (169.254.21.101)
[Evaluator::set_int64_variable] SENSORHEIGHT = 1088
AOIRowOffset read error: GigEVision read_register timeout
```
After that, the device must be power-cycled to respond again. I am leaving this aside, the device should not die when an out-of-range value is set.

The issue is that Aravis does not seem to finish evaluating the expression. Why? I tried running with `-d all:3`:
```
[Evaluator::set_double_variable] PI = 3.14159
[Evaluator::set_double_variable] E = 2.71828
[Gc::register_feature_node] Register node 'ArvGevStreamChannelSelectorMax' [IntSwissKnife]
[ArvDomCharacterData::set_data] Value = '  '
[ArvDomNode::append_child] Can't append '#text' to 'IntSwissKnife'
[ArvDomCharacterData::set_data] Value = 'NumberOfStreamChannels'
[ArvDomCharacterData::set_data] Value = '  '
[ArvDomNode::append_child] Can't append '#text' to 'IntSwissKnife'
[ArvDomCharacterData::set_data] Value = 'N_STREAM_CHANNELS - 1'
[GvDevice::new] Packet resend = yes
[GvDevice::new] Write memory = yes
[GvDevice::new] Legacy endianness handling = yes
VRmagicImaging-VRmLS1-GEV#128#018-660#C-EFD0AFMH07 (169.254.21.101)
[GcRegisterNode::_set_integer_value] address = 0xc134, value = 0x7d0
[GcRegisterNode::_get_integer_value] address = 0xc250, value = 0x440
[Evaluator::set_int64_variable] SENSORHEIGHT = 1088
[GvDevice::read_register] Ack reception timeout
[GvDevice::read_register] Ack reception timeout
[GvDevice::read_register] Ack reception timeout
[GvDevice::read_register] Ack reception timeout
```
Look at this:

```
[GcRegisterNode::_set_integer_value] address = 0xc134, value = 0x7d0
[GcRegisterNode::_get_integer_value] address = 0xc250, value = 0x440
[Evaluator::set_int64_variable] SENSORHEIGHT = 1088
```
The first line sets `0xc134` which is `AOIRowOffsetReg` to the garbage value, **before** `OffSetYMAX` is evaluated. The other lines reads `ImageSensorHeightReg` and set the variable `SENSORHEIGHT`. Meanwhile, the device stops responding, killed by the out-of-range value set.

The reverse order is confirmed for setting a valid `AOIRowOffset=0` value with `-d all:3`:

```
VRmagicImaging-VRmLS1-GEV#128#018-660#C-EFD0AFMH07 (169.254.21.101)
[GcRegisterNode::_set_integer_value] address = 0xc134, value = 0x0
[GcRegisterNode::_get_integer_value] address = 0xc250, value = 0x440
[Evaluator::set_int64_variable] SENSORHEIGHT = 1088
[GcRegisterNode::_get_integer_value] address = 0xc13c, value = 0x440
[Evaluator::set_int64_variable] HEIGHT = 1088
[Evaluator::evaluate_as_int64] Expression = 'SENSORHEIGHT - HEIGHT'
[Evaluator::parse_expression] SENSORHEIGHT - HEIGHT
[Evaluator::parse_expression] Found 3 items in expression
[Evaluator::parse_expression] 0 items in garbage list
[Evaluator::parse_expression] 3 items in token list
[Evaluator::evaluate_as_int64] Parsing status = 0
(var) SENSORHEIGHT = 1088
(var) HEIGHT = 1088
(operator) -
[Evaluator::evaluate] Result = (int64) 0
[GcRegisterNode::_get_integer_value] address = 0xc134, value = 0x0
AOIRowOffset = 0 min:0 max:0 inc:2
```

where again first the register `0xc134` is written, the expression only evaluated afterwards.

**Expected behavior**
`Min`/`Max` values should be evaluated **before** the register is written, and error should be reported for out-of-range.

**Camera description:**
 - VRmagic
 - LineScan3E
 - GigEVision

**Platform description:**
 - Aravis version: 0.8 (git)
 - OS: Ubuntu 20.04
 - Hardware: x86_64

**Comment by EmmanuelP** [comment] 2021-01-21 08:51
Hi,

Thanks for the report.

It is a duplicate of #270 

In arv-tool, bounds are read only for display, it was not intended for value validity check.

**Closed** 2021-01-21 08:51 UTC
Labels: 1. bug, 5. Genicam
