### ISSUE TITLE
OSX make error in realtimetest.c

### ISSUE THREAD

**Issue by cnsla** [AravisProject/aravis#92] opened 2017-08-02 16:11 UTC
realtimetest.c: In function ‘print_status’:
realtimetest.c:51:2: warning: implicit declaration of function ‘sched_getscheduler’ [-Wimplicit-function-declaration]
  if ((ret = sched_getscheduler(0)) < 0) {
  ^
realtimetest.c:64:3: warning: implicit declaration of function ‘sched_getparam’ [-Wimplicit-function-declaration]
   if (sched_getparam(0, &param) < 0) {
   ^
  CCLD     realtime-test
Undefined symbols for architecture x86_64:
  "_sched_getparam", referenced from:
      _print_status in realtimetest.o
  "_sched_getscheduler", referenced from:
      _print_status in realtimetest.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [realtime-test] Error 1
make: *** [all-recursive] Error 1

**Comment by EmmanuelP** [comment] 2017-08-02 16:13
Duplicate of https://github.com/AravisProject/aravis/issues/78

**Closed by EmmanuelP** 2017-08-02 16:13 UTC
